# Generated by Django 4.2.7 on 2023-11-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consumer',
            fields=[
                ('id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('pp', models.ImageField(default=None, null=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='airConditioner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('watts', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.consumer')),
            ],
        ),
    ]
