# Generated by Django 4.2.7 on 2023-11-30 11:54

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='pp',
            field=models.ImageField(default=None, null=True, storage=storages.backends.s3.S3Storage, upload_to=''),
        ),
    ]
