# Generated by Django 4.2.7 on 2023-11-30 12:28

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_consumer_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='pp',
            field=models.ImageField(default=None, null=True, storage=authentication.models.S3MediaStorage, upload_to=''),
        ),
    ]
