# Generated by Django 4.2.7 on 2023-11-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_consumer_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='pp',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
